---
name: 🚀 Enterprise Feature Request
description: Request a new feature for QuantumForge Enterprise Platform
title: "[FEATURE] - "
labels: ["enhancement", "enterprise", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Enterprise Feature Request

        Thank you for your feature suggestion! Enterprise feature requests help us prioritize development based on customer needs.

        **Please provide detailed information about your requested feature.**

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to your organization?
      options:
        - Critical - Required for production deployment
        - High - Important for business operations
        - Medium - Would improve efficiency
        - Low - Nice to have enhancement
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization
      description: Your organization name (for Enterprise prioritization)
      placeholder: "Acme Corporation"
    validations:
      required: false

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: "Describe the current limitation or pain point"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "How should this feature work?"
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "List any alternative solutions you've considered"
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which QuantumForge component would this feature affect?
      options:
        - Frontend UI/UX
        - Backend API
        - Quantum Processing Engine
        - MotherAI Assistant
        - Workflow Canvas
        - Security & Authentication
        - Database & Storage
        - Monitoring & Analytics
        - Deployment & Infrastructure
        - Integration & APIs
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: quantum-relevance
    attributes:
      label: Quantum Computing Relevance
      description: How does this feature relate to quantum computing?
      options:
        - Core quantum algorithm functionality
        - Quantum hardware integration
        - Quantum security enhancement
        - Performance optimization with quantum advantage
        - Quantum-inspired classical algorithms
        - Not quantum-related
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        As a [user type], I want [goal] so that [benefit].

        Example:
        As a quantum algorithm developer, I want to visualize circuit execution in real-time so that I can debug quantum programs more effectively.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What must be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature can be accessed from [location]
        - [ ] Feature works with [quantum backend]
        - [ ] Feature includes [documentation/testing]
        - [ ] Feature meets [performance requirements]
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: What is the business impact of this feature?
      placeholder: "Describe ROI, efficiency gains, competitive advantage, etc."
    validations:
      required: false

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature implemented?
      placeholder: "Q1 2025, Within 6 months, ASAP"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or references
      placeholder: "Add screenshots, links to similar features, technical details, etc."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm these items
      options:
        - label: I have searched existing feature requests for duplicates
          required: true
        - label: This feature would benefit multiple organizations
          required: true
        - label: I am willing to provide feedback during development
          required: true
        - label: I understand this may be subject to prioritization and roadmap planning
          required: true